basePath: /api/v1
definitions:
  main.Item:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample REST API with Swagger documentation.
  title: BASICAPI_with_Swagger
  version: "1.0"
paths:
  /items:
    get:
      description: Get all items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Item'
            type: array
      summary: Get a list of items
  /items/{id}:
    get:
      description: Get details of a specific item
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Item'
      summary: Get item by ID
swagger: "2.0"
